name: make_your_vibe
description: Make Your Vibe Android progress rebuild with separated screens.
publish_to: 'none'
version: 0.4.7+47

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.6
  shared_preferences: ^2.5.5
  http: ^1.6.0
  audio_session: ^0.2.4
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.19
  youtube_explode_dart: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
