import 'package:flutter/material.dart';

class SystemAlbum {
  final String id;
  final String title;
  final String subtitle;
  final String query;
  final List<String> trackQueries;
  final IconData icon;
  final String coverUrl;

  const SystemAlbum({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.query,
    this.trackQueries = const [],
    required this.icon,
    required this.coverUrl,
  });
}

const systemAlbums = [
  SystemAlbum(
    id: 'cho-bao',
    title: 'Cho Bảo',
    subtitle: 'B Ray • The Album',
    query: 'B Ray Cho Bảo album',
    trackQueries: [
      'B Ray Cho Bảo Intro',
      'B Ray Vùng An Toàn V# Cho Bảo',
      'B Ray The One Đạt G Cho Bảo',
      'B Ray Viết Em Bản Tình Ca Cho Bảo',
      'B Ray Ghệ Mới Young H Cho Bảo',
      'B Ray Y Chang Em Cho Bảo',
      'B Ray Feel At Home Cho Bảo',
      'B Ray Selfish Man Cho Bảo',
      'B Ray Không Thuộc Về Nơi Này Cho Bảo',
      'B Ray Còn Ai Ngoài Anh Với Em Cho Bảo',
      'B Ray Are You Sad Cho Bảo',
    ],
    icon: Icons.album_rounded,
    coverUrl: 'https://i.ytimg.com/vi/tcV47TTTU_U/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'danh-doi',
    title: 'Đánh Đổi',
    subtitle: 'Obito, Shiki • Album',
    query: 'Obito Đánh Đổi album',
    trackQueries: [
      'Obito Đánh Đổi Album Intro',
      'Obito Xuất Phát Điểm Đánh Đổi',
      'Obito CL5 interlude Đánh Đổi',
      'Obito Đầu Đường Xó Chợ Lăng LD',
      'Obito Biên Giới Long Bình Đánh Đổi',
      'Obito 16 Đánh Đổi',
      'Obito Sài Gòn ơi Đánh Đổi',
      'Obito Trốn Chạy Đánh Đổi',
      'Obito Cất Cánh interlude Đánh Đổi',
      'Obito Hà Nội VSTRA Đánh Đổi',
      'Obito Vô Điều Kiện Đánh Đổi',
      'Obito Đánh Đổi RPT MCK Shiki',
      'Obito Backstage Freestyle Đánh Đổi',
      'Obito Tell The Kids I Love Them Shiki',
      'Obito Ước Mơ Của Mẹ interlude Đánh Đổi',
      'Obito Con Kể Ba Nghe Đánh Đổi',
      'Obito Champion Đánh Đổi',
      'Obito Chưa Xong Đánh Đổi',
      'Obito Tự Sự Đánh Đổi',
      'Obito Outro Đánh Đổi',
    ],
    icon: Icons.blur_on_rounded,
    coverUrl: 'https://i.ytimg.com/vi/PKEqsBIW41k/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'mck-99',
    title: '99%',
    subtitle: 'RPT MCK • Album',
    query: 'RPT MCK 99 album',
    trackQueries: [
      'RPT MCK 00 Intro 99 album',
      'RPT MCK Chìm Sâu Trung Trần 99 album',
      'RPT MCK Suit & Tie Hoàng Tôn 99 album',
      'RPT MCK Va Vào Giai Điệu Này 99 album',
      'RPT MCK Tối Nay Ta Đi Đâu Nhờ 99 album',
      'RPT MCK Chỉ Một Đêm Nữa Thôi tlinh 99 album',
      'RPT MCK Thôi Em Đừng Đi Trung Trần 99 album',
      'RPT MCK Cuốn Cho Anh Một Điếu Nữa Đi 99 album',
      'RPT MCK Tại Vì Sao 99 album',
      'RPT MCK Anh Đã Ổn Hơn 99 album',
      'RPT MCK Badtrip 99 album',
      'RPT MCK 99 99 album',
    ],
    icon: Icons.graphic_eq_rounded,
    coverUrl: 'https://i.ytimg.com/vi/sYSvC8tOgKE/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'acpbdtdd',
    title: 'Ai Cũng Phải Bắt Đầu Từ Đâu Đó',
    subtitle: 'HIEUTHUHAI • Album',
    query: 'HIEUTHUHAI Ai Cũng Phải Bắt Đầu Từ Đâu Đó album',
    trackQueries: [
      'HIEUTHUHAI Ai Cũng Phải Bắt Đầu Từ Đâu Đó',
      'HIEUTHUHAI Giờ Thì Ai Cười',
      'HIEUTHUHAI Không Phải Gu B Ray Tage',
      'HIEUTHUHAI Siêu Sao',
      'HIEUTHUHAI Đi Họp Lớp',
      'HIEUTHUHAI Không Thể Say',
      'HIEUTHUHAI Exit Sign',
      'HIEUTHUHAI Visa Interlude',
      'HIEUTHUHAI Sắp Nổi Tiếng',
      'HIEUTHUHAI KPI',
      'HIEUTHUHAI Everything Will Be Okay',
      'HIEUTHUHAI Cho Em An Toàn',
      'HIEUTHUHAI NOLOVENOLIFE',
    ],
    icon: Icons.auto_awesome_rounded,
    coverUrl: 'https://i.ytimg.com/vi/2rvMy0Itg1E/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'vu-tru-co-bay',
    title: 'Vũ Trụ Cò Bay',
    subtitle: 'Phương Mỹ Chi • Album',
    query: 'Phương Mỹ Chi Vũ Trụ Cò Bay album',
    trackQueries: [
      'Phương Mỹ Chi Vũ Trụ Cò Bay',
      'Phương Mỹ Chi Gối Gấm',
      'Phương Mỹ Chi Đẩy Xe Bò',
      'Phương Mỹ Chi Vũ Trụ Có Anh DTAP',
      'Phương Mỹ Chi Những Ngôi Sao Xa Xôi',
      'Phương Mỹ Chi Bóng Phù Hoa',
      'Phương Mỹ Chi Chiếc Lược Ngà',
      'Phương Mỹ Chi Hai Đứa Trẻ',
      'Phương Mỹ Chi Chiếc Thuyền Ngoài Xa',
      'Phương Mỹ Chi Người Con Gái Nằm Nghe Biển Hát',
    ],
    icon: Icons.theater_comedy_rounded,
    coverUrl: 'https://i.ytimg.com/vi/EKFsQgh6QcE/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'lowg-l2k',
    title: 'L2K',
    subtitle: 'Low G • Album',
    query: 'Low G L2K album',
    trackQueries: [
      'Low G Intro Rap Zone L2K',
      'Low G Siêu Sao L2K',
      'Low G Nét L2K',
      'Low G Đừng Để Tiền Rơi L2K',
      "Low G Peace N' Love Mỹ Anh L2K",
      'Low G Interlude 1 Cửa Sổ Tình Yêu L2K',
      'Low G Love Game L2K',
      'Low G Giải Cứu Mỹ Nhân L2K',
      'Low G Interlude 2 Lời Nhắn Từ Thính Giả L2K',
      'Low G In Love L2K',
      'Low G Nhiều Hơn L2K',
      'Low G Tràng Thi L2K',
      'Low G Long L2K',
      'Low G Celeb Date L2K',
      'Low G Outro L2K FM',
    ],
    icon: Icons.radio_rounded,
    coverUrl: 'https://i.ytimg.com/vi/tj4k33OMkC4/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'thien-ha',
    title: 'Thiên hạ nghe gì',
    subtitle: 'Hot V-Pop hôm nay',
    query: 'nhac tre viet nam hot nhat hien nay official music',
    trackQueries: [
      'Hòa Minzy Bắc Bling official',
      'Dương Domic Mất Kết Nối official',
      'HIEUTHUHAI Không Thể Say official',
      'HIEUTHUHAI Exit Sign official',
      'Obito Đánh Đổi official audio',
      'RPT MCK Chìm Sâu Trung Trần official',
      'tlinh nếu lúc đó official',
      'Sơn Tùng M-TP Đừng Làm Trái Tim Anh Đau official',
      'Đức Phúc Chăm Em Một Đời official',
      'Erik Dù Cho Tận Thế official',
      'Vũ Cát Tường Từng Là official',
      'Quang Hùng MasterD Trói Em Lại official',
      'RHYDER Chịu Cách Mình Nói Thua official',
      'Orange Có Đau Thì Đau Một Mình official',
      'GREY D Thiên Thanh official',
      'Phương Mỹ Chi Vũ Trụ Có Anh official',
      'Low G Peace N Love Mỹ Anh official',
      'B Ray Cưới Thôi official',
    ],
    icon: Icons.local_fire_department_rounded,
    coverUrl: 'https://i.ytimg.com/vi/kPa7bsKwL-c/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'top-100',
    title: 'Top nhạc Việt hay',
    subtitle: 'V-Pop nghe hoài vẫn cuốn',
    query: 'top 100 nhac viet hay nhat vpop official audio',
    trackQueries: [
      'Sơn Tùng M-TP Chúng Ta Của Hiện Tại official',
      'Sơn Tùng M-TP Nơi Này Có Anh official',
      'Sơn Tùng M-TP Lạc Trôi official',
      'Miu Lê Vì Mẹ Anh Bắt Chia Tay official',
      'Erik Sau Tất Cả official',
      'Đức Phúc Ánh Nắng Của Anh official',
      'Hòa Minzy Rời Bỏ official',
      'Hương Tràm Em Gái Mưa official',
      'Trung Quân Chưa Bao Giờ official',
      'Bích Phương Bùa Yêu official',
      'MIN Có Em Chờ official',
      'Da LAB Thanh Xuân official',
      'Vũ Lạ Lùng official',
      'Chillies Vùng Ký Ức official',
      'AMEE Anh Nhà Ở Đâu Thế official',
      'JustaTee Đã Lỡ Yêu Em Nhiều official',
      'Soobin Phía Sau Một Cô Gái official',
      'Noo Phước Thịnh Cause I Love You official',
    ],
    icon: Icons.emoji_events_rounded,
    coverUrl: 'https://i.ytimg.com/vi/knW7-x7Y7RE/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'rap-viet',
    title: 'Rap Việt',
    subtitle: 'B Ray, HIEUTHUHAI, Obito',
    query: 'rap viet bray hieuthuhai obito official mv',
    trackQueries: [
      'Obito Đánh Đổi official audio',
      'Obito Hà Nội VSTRA official audio',
      'HIEUTHUHAI Ngủ Một Mình official',
      'HIEUTHUHAI Không Thể Say official',
      'B Ray Anh Luôn Như Vậy official',
      'B Ray Cưới Thôi official',
      'Low G An Thần official',
      "Low G Peace N' Love Mỹ Anh official",
      'RPT MCK Chìm Sâu Trung Trần official',
      'RPT MCK Tại Vì Sao official',
      'tlinh vaicaunoicokhiennguoithaydoi official',
      'Wxrdie Chơi Như Tụi Mỹ official',
      '24k.Right Chơi Như Tụi Mỹ official',
      'Robber Đừng Làm Anh Đau official',
      'GILL Thiên Lý Ơi official',
      'Mikelodic Nàng Thơ official',
    ],
    icon: Icons.mic_external_on_rounded,
    coverUrl: 'https://i.ytimg.com/vi/9hR9YEFYZ3s/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'son-tung',
    title: 'Sơn Tùng M-TP',
    subtitle: 'Album ca sĩ',
    query: 'Son Tung M-TP official music video',
    trackQueries: [
      'Son Tung M-TP Hay Trao Cho Anh official',
      'Son Tung M-TP Lac Troi official',
      'Son Tung M-TP Noi Nay Co Anh official',
      'Son Tung M-TP Chung Ta Cua Hien Tai official',
      'Son Tung M-TP Co Chac Yeu La Day official',
      'Son Tung M-TP Muon Roi Ma Sao Con official',
    ],
    icon: Icons.star_rounded,
    coverUrl: 'https://i.ytimg.com/vi/knW7-x7Y7RE/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'chill-vpop',
    title: 'Chill V-Pop',
    subtitle: 'Nghe nhẹ buổi tối',
    query: 'chill vpop lofi viet nam official audio',
    trackQueries: [
      'Vũ Lạ Lùng official',
      'Vũ Bước Qua Nhau official',
      'Da LAB Thanh Xuân official',
      'Chillies Vùng Ký Ức official',
      'Chillies Mascara official',
      'Cá Hồi Hoang Tháng Tư Là Lời Nói Dối Của Em official',
      'Ngọt Em Dạo Này official',
      'The Cassette Khoảng Cách official',
      'The Flob Có Quá Nhiều Điều official',
      'Madihu Có Em official',
      'Trang Và Khi Ta Ngả Nghiêng official',
      'GREY D Thiên Thanh official',
    ],
    icon: Icons.nights_stay_rounded,
    coverUrl: 'https://i.ytimg.com/vi/J7C4Ue7Iry0/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'ballad',
    title: 'Ballad Việt',
    subtitle: 'Tình ca, acoustic',
    query: 'ballad viet acoustic official audio',
    trackQueries: [
      'Duc Phuc Anh Nang Cua Anh official',
      'Erik Cham Day Noi Dau official',
      'Hoa Minzy Roi Bo official',
      'Trung Quan Chua Bao Gio official',
      'Bui Anh Tuan Noi Tinh Yeu Bat Dau official',
      'Huong Tram Em Gai Mua official',
    ],
    icon: Icons.favorite_rounded,
    coverUrl: 'https://i.ytimg.com/vi/1zyzVj89y9I/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'remix',
    title: 'EDM Remix',
    subtitle: 'Năng lượng cao',
    query: 'nhac viet remix edm hot official',
    trackQueries: [
      'Hoaprox Ngau Hung official',
      'K-ICM Buon Cua Anh official',
      'Jack Bac Phan official',
      'Son Tung M-TP Hay Trao Cho Anh official',
      'Min Co Em Cho official',
      'Toc Tien Vu Dieu Cong Chieng official',
    ],
    icon: Icons.bolt_rounded,
    coverUrl: 'https://i.ytimg.com/vi/uelHwf8o7_U/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'study',
    title: 'Lofi học bài',
    subtitle: 'Tập trung, nhẹ đầu',
    query: 'lofi hoc bai viet nam chill beats',
    trackQueries: [
      'lofi viet nam chill hoc bai',
      'chillhop viet nam lofi',
      'piano viet nam thu gian',
      'acoustic chill viet nam',
      'lofi coffee vietnam',
      'nhac khong loi chill hoc bai',
      'lofi study beats no copyright',
      'jazzhop study playlist',
      'piano lofi sleep study',
      'nhac khong loi tap trung lam viec',
      'rainy lofi study music',
      'coffee shop ambience lofi',
    ],
    icon: Icons.school_rounded,
    coverUrl: 'https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg',
  ),
  SystemAlbum(
    id: 'sleep-chill',
    title: 'Chill dễ ngủ',
    subtitle: 'Êm, nhẹ, ít làm tỉnh đầu',
    query: 'nhac chill de ngu viet nam lofi',
    trackQueries: [
      'nhạc chill dễ ngủ không lời',
      'lofi sleep vietnam',
      'piano nhẹ nhàng dễ ngủ',
      'rain sleep lofi music',
      'acoustic chill sleep vietnam',
      'nhạc mưa thư giãn dễ ngủ',
      'soft piano sleep music',
      'lofi night sleep playlist',
      'calm guitar sleep music',
      'nhạc thư giãn trước khi ngủ',
      'ambient sleep music rain',
      'deep sleep lofi instrumental',
    ],
    icon: Icons.bedtime_rounded,
    coverUrl: 'https://i.ytimg.com/vi/28KRPhVzCus/hqdefault.jpg',
  ),
];
